### ISSUE TITLE
NameError: name 'args_utils' is not defined

### ISSUE THREAD

**Issue by WhaleGe** [Patchouli-M/SequencingCancerFinder#3]
Thank you very much for providing such a useful package. This is more convenient for us to find tumor cells. However, I encountered some errors when running the demo, I would like to ask for your help.

This is my script

```bash
/home/conda/envs/scf/bin/python -u /home/data/CancerFinder/infer.py --ckp=/home/data/CancerFinder/sc_pretrain_article.pkl --matrix=/home/data/CancerFinder/sample_data_matrix.tsv --out=out.csv
```
* first error
Traceback (most recent call last):
  File "/jdfssz1/ST_HEALTH/P21Z10200N0134/USER/huangwaidong/CancerFinder/infer.py", line 4, in <module>
    from models import model
**ImportError: cannot import name 'model' from 'models' (unknown location)**

For the first error, I changed _from models import model_ to _import models_ and it continued to run

* second error
Traceback (most recent call last):
  File "/home/data/CancerFinder/infer.py", line 12, in <module>
    args = args_utils.infer_args()
**NameError: name 'args_utils' is not defined**

But for the second question, I didn't find the answer online

**Comment by Patchouli-M** [comment]
Thank you for your interest.This error seems to indicate that the working directory hasn't been set correctly.

"models" and "args_utils" are two folders within the code, and infer.py needs to import code from these two folders.

If you have downloaded the complete code, I suggest you run the following command directly on a Linux system:

```
cd /home/data/CancerFinder
/home/conda/envs/scf/bin/python -u infer.py --ckp=checkpoints/sc_pretrain_article.pkl --matrix=sample_data/sample_data_matrix.tsv --out=out.csv
```

It's necessary to "cd" to the project folder.

If you are using an IDE or another editor like VSCode, I would suggest looking into the settings related to the working directory.

**Comment by Patchouli-M** [comment]
Thank you for your interest.This error seems to indicate that the working directory hasn't been set correctly.

"models" and "args_utils" are two folders within the code, and infer.py needs to import code from these two folders.

If you have downloaded the complete code, I suggest you run the following command directly on a Linux system:
```
cd /home/data/CancerFinder
/home/conda/envs/scf/bin/python -u infer.py --ckp=checkpoints/sc_pretrain_article.pkl --matrix=sample_data/sample_data_matrix.tsv --out=out.csv
```
It's necessary to "cd" to the project folder.

If you are using an IDE or a remote editor (such as VSCode), I would suggest looking into the settings related to the working directory.

**Comment by Patchouli-M** [comment]
Thank you for your interest. This error seems to indicate that the working directory hasn't been set correctly.

"models" and "args_utils" are two folders within the code, and infer.py needs to import code from these two folders.

If you have downloaded the complete code, I suggest you run the following commands directly on a Linux system:
```
cd /home/data/CancerFinder
/home/conda/envs/scf/bin/python -u infer.py --ckp=checkpoints/sc_pretrain_article.pkl --matrix=sample_data/sample_data_matrix.tsv --out=out.csv
```
It's necessary to "cd" to the project folder.

If you are using an IDE or a remote editor (such as VSCode), I would suggest looking into the settings related to the working directory.

**Comment by xianjieshen** [comment]
I'm really pleased that the author has developed such a useful package; it represents a significant advancement in oncology. I encountered the same issue and resolved it by following the author's instructions: use the cd command in a Linux environment to navigate to the directory where your infer.py is stored. Then download the folders provided by the author, namely "models" and "utils," and save them to this directory. After doing so, you should be able to run it successfully.
![image](https://github.com/Patchouli-M/SequencingCancerFinder/assets/21005642/d0db095f-646b-4c27-a061-52106462df29)
